server:
  port: 43941

spring:
  mvc:
    async:
      request-timeout: 500
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://[@4394-TDSQL_VIP]:[@4394-TDSQL_PORT]/wsdawconfig?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: [*user_WSDAWCONFIG]
    password: [*pass_WSDAWCONFIG]
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    defaultAutoCommit: false
    druid:
      initialSize: 25
      maxActive: 128
      minIdle: 25
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 34000
      minEvictableIdleTimeMillis: 34000
      removeAbandoned: false
      logAbandoned: true
      removeAbandonedTimeout: 54
      maxWait: 10000
      poolPreparedStatements: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  typeAliasesPackage: com.webank.wsdaw.config.dao.entity
  configuration:
    map-underscore-to-camel-case: true

servlet:
  context-path: /api

system:
  encrypt-private-key: [*key_wsdawEncryptPrivateKey]

logging:
  config: config/logback-spring.xml

